apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "v2ray.name" . }}
    helm.sh/chart: {{ include "v2ray.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.vmess.port }}
      targetPort: {{ .Values.vmess.port }}
      protocol: TCP
      name: vmess
    - port: {{ .Values.ss.port }}
      targetPort: {{ .Values.ss.port }}
      protocol: TCP
      name: ss
  selector:
    app.kubernetes.io/name: {{ include "v2ray.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
